#!/bin/sh

windowClass=$1
appExecutable=$2

if [ $# -eq 0 ]; then
  echo focusOrStart: you need to specify at least a window name.
  exit 1
fi

if [ -z $2 ]; then
  appExecutable=$windowClass
fi

wmctrl -x -a "$windowClass" || $appExecutable
