#!/bin/sh

# From instructions here: https://gist.github.com/cryzed/e002e7057435f02cc7894b9e748c5671

# 1. Install font packages
# yay -S fonts-meta-extended-lt fonts-meta-base ttf-emojione --noconfirm
