#!/bin/sh

# -----------------------------------------
# SPACEHSHIP OPTIONS
# https://github.com/denysdovhan/spaceship-prompt/blob/master/docs/Options.md
# -----------------------------------------

SPACESHIP_CHAR_SYMBOL="\u$CODEPOINT_OF_OCTICONS_CHEVRON_RIGHT"
SPACESHIP_CHAR_SUFFIX=" "
SPACESHIP_GIT_BRANCH_PREFIX="\u$CODEPOINT_OF_DEVICONS_GIT_BRANCH "
SPACESHIP_PACKAGE_COLOR="yellow"
SPACESHIP_PACKAGE_SYMBOL="\u$CODEPOINT_OF_OCTICONS_PACKAGE "
SPACESHIP_PHP_SYMBOL="\u$CODEPOINT_OF_DEVICONS_PHP "
SPACESHIP_DOCKER_SYMBOL="\u$CODEPOINT_OF_DEVICONS_DOCKER "
SPACESHIP_PYENV_SYMBOL="\u$CODEPOINT_OF_DEVICONS_PYTHON "
SPACESHIP_GIT_STATUS_STASHED="∙"